[tools]
# Stack
node = "lts"
pnpm = "latest"
rust = "latest"

# Tools
fnox = "latest"
opencode = "latest"

[env]
_.source = "scripts/env.sh"

[settings]
experimental = true
idiomatic_version_file_enable_tools = ["rust"] # Use rust-toolchain.toml
